[project]
src = "src"
out = "out"
dot_env = ".env"
"save_abi_path" = "abis"
default_network_name = "eth-forked"

[networks.contracts]
weth = { abi = "abis/weth.json" }
usdc = { abi = "abis/usdc.json" }
aave_pool_address_provider = { abi = "abis/aave_pool_address_provider.json" }
pool = { abi = "abis/pool.json" }
aave_protocol_data_provider = { abi = "abis/aave_protocol_data_provider.json" }
eth_usd = { abi = "abis/eth_usd.json" }
usdc_usd = { abi = "abis/usdc_usd.json" }
uniswap_swap_router = { abi = "abis/uniswap_swap_router.json" }
wbtc = { abi = "abis/wbtc.json" }
link = { abi = "abis/link.json" }

[networks.pyevm]
is_zksync = false

# Note: we can't actually run on just Anvil, we need the forked network to have
# the mainnet contracts available.
[networks.anvil]
url = "http://127.0.0.1:8545"
default_account_name = "anvil0"
unsafe_password_file = "$ANVIL0_PASSWORD_FILE"
prompt_live = false
save_to_db = false
chain_id = 31337

[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

[networks.eth-forked]
fork = true
url = "$MAINNET_RPC_URL"
default_account_name = "anvil0"
unsafe_password_file = "$ANVIL0_PASSWORD_FILE"

[networks.eth-forked.contracts]
usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"}
weth = { address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2" }
aave_pool_address_provider = { address = "0x2f39d218133AFaB8F2B819B1066c7E434Ad94E9e" }
aave_protocol_data_provider = { address = "0x0a16f2FCC0D44FaE41cc54e079281D84A363bECD" }
eth_usd = { address = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419" }
usdc_usd = { address = "0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6" }
uniswap_swap_router = { address = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45" }
wbtc = { address = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599" }
link = { address = "0x514910771AF9Ca656af840dff83E8264EcF986CA" }

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
