[project]
name = "Alogorithmic_Trading_Project"
version = "0.1.0"
description = "Balancing a portfolio of WETH and USDC on a forked Ethereum mainnet using moccasin."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["moccasin"]
